services:
  master:
    image: postgres:16.2-alpine3.19
    container_name: primary_db
    volumes:
      - logical-primary-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    restart: unless-stopped
    ports:
      - "5400:5432"
  replica:
    image: postgres:16.2-alpine3.19
    container_name: replica_db
    volumes:
      - logical-replica-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    restart: unless-stopped
    ports:
      - "5401:5432"
volumes:
  logical-primary-db-data:
    name: logical-primary-db-data
  logical-replica-db-data:
    name: logical-replica-db-data

